# Generated by Django 4.2.30 on 2026-05-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='resumen',
            field=models.TextField(blank=True, help_text='Breve resumen del libro', null=True),
        ),
    ]
